package ec.gov.senplades.planificador;

/**
*
* @author jalvarado
*/
public class fDZonaRiesgo extends javax.swing.JFrame {

   /** Creates new form DzonaRiesgo */
	boolean bNuevo;  
   public fDZonaRiesgo(boolean bNuevo) {
       initComponents();
       setVisible(true);
       this.bNuevo = bNuevo; 
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   private void initComponents() {

       jLabel1 = new javax.swing.JLabel();
       cmdAceptar = new javax.swing.JButton();
       txtProvincia = new javax.swing.JTextField();
       jLabel2 = new javax.swing.JLabel();
       jLabel3 = new javax.swing.JLabel();
       txtCanton = new javax.swing.JTextField();
       jLabel4 = new javax.swing.JLabel();
       txtParroquia = new javax.swing.JTextField();
       jLabel5 = new javax.swing.JLabel();
       txtAreaCensal = new javax.swing.JTextField();
       cmbTipoRiesgo = new javax.swing.JComboBox();

       //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
       setTitle("Datos de Zonas de Riesgo");

       jLabel1.setText("Provincia");

       cmdAceptar.setText("Aceptar");
       cmdAceptar.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               cmdAceptarActionPerformed(evt);
           }
       });

       jLabel2.setText("Tipo de Riesgo");
       jLabel3.setText("Canton");

       txtCanton.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               txtCantonActionPerformed(evt);
           }
       });

       jLabel4.setText("Paroquia");

       jLabel5.setText("Area Censal");

       cmbTipoRiesgo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Riesgo Volcanico", "Inundación", "Movimiento de tierras" }));

       if (!bNuevo) {
           txtProvincia.setText("Pichincha"); 
           txtCanton.setText("Rumiñahui");
           txtParroquia.setText("Sangolqui");
           txtAreaCensal.setText("170201562001");
           cmbTipoRiesgo.setSelectedIndex(0 ); 

       }
       
       
       
       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addGap(164, 164, 164)
                       .addComponent(cmdAceptar))
                   .addGroup(layout.createSequentialGroup()
                       .addGap(30, 30, 30)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                           .addGroup(layout.createSequentialGroup()
                               .addComponent(jLabel3)
                               .addGap(30, 30, 30)
                               .addComponent(txtCanton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGroup(layout.createSequentialGroup()
                               .addComponent(jLabel1)
                               .addGap(30, 30, 30)
                               .addComponent(txtProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGroup(layout.createSequentialGroup()
                               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addComponent(jLabel2)
                                   .addComponent(jLabel5)
                                   .addComponent(jLabel4))
                               .addGap(30, 30, 30)
                               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(cmbTipoRiesgo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                   .addComponent(txtParroquia, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                   .addComponent(txtAreaCensal, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))))))
               .addContainerGap(91, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(37, 37, 37)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel1)
                   .addComponent(txtProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel3)
                   .addComponent(txtCanton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel4)
                   .addComponent(txtParroquia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel5)
                   .addComponent(txtAreaCensal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(cmbTipoRiesgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel2))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
               .addComponent(cmdAceptar)
               .addGap(21, 21, 21))
       );

       pack();
   }// </editor-fold>

   private void cmdAceptarActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
       setVisible(false);
   }

   private void txtCantonActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
   }

   /**
   * @param args the command line arguments
   */
   public static void main(String args[]) {
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new fDZonaRiesgo(false).setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify
   private javax.swing.JComboBox cmbTipoRiesgo;
   private javax.swing.JButton cmdAceptar;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JTextField txtAreaCensal;
   private javax.swing.JTextField txtCanton;
   private javax.swing.JTextField txtParroquia;
   private javax.swing.JTextField txtProvincia;
   // End of variables declaration

}
