package ec.gov.senplades.planificador;

/**
*
* @author jalvarado
*/
public class fIndicadores extends javax.swing.JFrame {

   /** Creates new form fInfraActual */
   public fIndicadores() {
       initComponents();
       setVisible(true); 
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   private void initComponents() {

       jScrollPane1 = new javax.swing.JScrollPane();
       tblTabla = new javax.swing.JTable();
       jPanel1 = new javax.swing.JPanel();
       cmdNuevo = new javax.swing.JButton();
       cmdEditar = new javax.swing.JButton();
       cmdEliminar = new javax.swing.JButton();
       cmdAceptar = new javax.swing.JButton();
       jScrollPane2 = new javax.swing.JScrollPane();
       jTable1 = new javax.swing.JTable();
       cmdNuevo1 = new javax.swing.JButton();
       cmdEditar1 = new javax.swing.JButton();
       cmdEliminar1 = new javax.swing.JButton();
       cmbPeriodo = new javax.swing.JComboBox();
       jLabel1 = new javax.swing.JLabel();
       jLabel2 = new javax.swing.JLabel();
       cmbTipoPeriodo = new javax.swing.JComboBox();
       cmdCancelar = new javax.swing.JButton();       

       //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
       setTitle("Indicadores");

       tblTabla.setModel(new javax.swing.table.DefaultTableModel(
           new Object [][] {
               {"SNI001", "Desempleo", "Descendente", "Nacional", "Porcentaje", "Si"},
               {"SNI002", "Embarzao adolecente", "Descendente", "Cantonal", "Porcentaje", "Si"},
               {"001", "Pobreza", "Descendente", "Area Censal", "Porcentaje", "No"},
               {"002", "Ingreso Promedio", "Ascendente", "Parroquial", "Dolares", "No"},
               {null, null, null, null, null, null}
           },
           new String [] {
               "Codigo", "Nombre", "Direccion ", "Nivel Agregacion", "Unidad Medida", "Fijo"
           }
       ));
       jScrollPane1.setViewportView(tblTabla);

       cmdNuevo.setText("Nuevo");
       cmdNuevo.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               cmdNuevoActionPerformed(evt);
           }
       });

       cmdEditar.setText("Editar");
       cmdEditar.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               cmdEditarActionPerformed(evt);
           }
       });

       cmdEliminar.setText("Eliminar");
       cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               cmdEliminarActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
       jPanel1.setLayout(jPanel1Layout);
       jPanel1Layout.setHorizontalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addComponent(cmdEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(cmdEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(cmdNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addContainerGap(17, Short.MAX_VALUE))
       );
       jPanel1Layout.setVerticalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(cmdNuevo)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(cmdEditar)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(cmdEliminar)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );

       cmdAceptar.setText("Aceptar");
       cmdAceptar.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               cmdAceptarActionPerformed(evt);
           }
       });

       jTable1.setModel(new javax.swing.table.DefaultTableModel(
           new Object [][] {
               {"0101", "42"},
               {"0102", "56"},
               {"0103", "67"},
               {"0104", "39"}
           },
           new String [] {
               "Ambito", "Valor"
           }
       ));
       jScrollPane2.setViewportView(jTable1);

       cmdNuevo1.setText("Nuevo");
       cmdNuevo1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               cmdNuevo1ActionPerformed(evt);
           }
       });

       cmdEditar1.setText("Editar");
       cmdEditar1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               cmdEditar1ActionPerformed(evt);
           }
       });

       cmdEliminar1.setText("Eliminar");
       cmdEliminar1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               cmdEliminar1ActionPerformed(evt);
           }
       });

       cmbPeriodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2007", "2008", "2009", "2010" }));

       jLabel1.setText("Periodo de tiempo");

       jLabel2.setText("Tipo Periodo de Tiempo");

       cmbTipoPeriodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Censal", "Anual", "Mensual" }));


       cmdCancelar.setText("Cancelar");
       cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               cmdCancelarActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap())
           .addGroup(layout.createSequentialGroup()
               .addGap(140, 140, 140)
               .addComponent(cmdAceptar)
               .addGap(131, 131, 131)
               .addComponent(cmdCancelar)
               .addContainerGap(176, Short.MAX_VALUE))
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                   .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                       .addComponent(jLabel2)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(cmbTipoPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                       .addComponent(jLabel1)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(cmbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addComponent(cmdEliminar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(cmdEditar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(cmdNuevo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGap(25, 25, 25))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(22, 22, 22)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel2)
                   .addComponent(cmbTipoPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel1)
                   .addComponent(cmbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(19, 19, 19)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(cmdCancelar)
                           .addComponent(cmdAceptar)))
                   .addGroup(layout.createSequentialGroup()
                       .addComponent(cmdNuevo1)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(cmdEditar1)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(cmdEliminar1)))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );

       pack();

   }// </editor-fold>

   private void cmdAceptarActionPerformed(java.awt.event.ActionEvent evt) {                                           
       // TODO add your handling code here:
       setVisible(false);
   }                                          

   private void cmdNuevoActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // TODO add your handling code here:
   }                                        

   private void cmdEditarActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {                                            
       // TODO add your handling code here:
   }                                           

   private void cmdNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
   }

   private void cmdEditar1ActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
   }

   private void cmdEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
   }

   private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
	   setVisible(false); 
   }

   
   
   /**
   * @param args the command line arguments
   */
   public static void main(String args[]) {
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new fIndicadores().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify
   private javax.swing.JComboBox cmbPeriodo;
   private javax.swing.JComboBox cmbTipoPeriodo;
   private javax.swing.JButton cmdAceptar;
   private javax.swing.JButton cmdEditar;
   private javax.swing.JButton cmdEditar1;
   private javax.swing.JButton cmdEliminar;
   private javax.swing.JButton cmdEliminar1;
   private javax.swing.JButton cmdNuevo;
   private javax.swing.JButton cmdNuevo1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JTable jTable1;
   private javax.swing.JTable tblTabla;
   private javax.swing.JButton cmdCancelar;
   // End of variables declaration

}
