package ec.gov.senplades.planificador;

/**
*
* @author jalvarado
*/
public class fInsumos extends javax.swing.JFrame {

   /** Creates new form fInfraActual */
   public fInsumos() {
       initComponents();
       setVisible(true); 
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   private void initComponents() {

       jScrollPane1 = new javax.swing.JScrollPane();
       tblTabla = new javax.swing.JTable();
       jPanel1 = new javax.swing.JPanel();
       cmdNuevo = new javax.swing.JButton();
       cmdEditar = new javax.swing.JButton();
       cmdEliminar = new javax.swing.JButton();
       cmdAceptar = new javax.swing.JButton();
       jLabel1 = new javax.swing.JLabel();
       cmbTipoEstablecimiento = new javax.swing.JComboBox();
       cmdCancelar = new javax.swing.JButton();       

       //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
       setTitle("Insumos");

       tblTabla.setModel(new javax.swing.table.DefaultTableModel(
           new Object [][] {
               {"34232", "Urea", "Kg", "17.54", "13-Jun-2005"},
               {"24222", "Potasio", "Kg", "0.67", "13-Jun-2005"},
               {"56452", "Saquillo", "Unidad", "0.12", "22-Enero-2007"},
               {null, null, null, null, null},
               {null, null, null, null, null}
           },
           new String [] {
               "Codigo", "Nombre", "Unidad Medida ", "Costo Unitario", "Fecha Costo"
           }
       ));
       jScrollPane1.setViewportView(tblTabla);

       cmdNuevo.setText("Nuevo");
       cmdNuevo.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               cmdNuevoActionPerformed(evt);
           }
       });

       cmdEditar.setText("Editar");
       cmdEditar.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               cmdEditarActionPerformed(evt);
           }
       });

       cmdEliminar.setText("Eliminar");
       cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               cmdEliminarActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
       jPanel1.setLayout(jPanel1Layout);
       jPanel1Layout.setHorizontalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addComponent(cmdEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(cmdEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(cmdNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addContainerGap(17, Short.MAX_VALUE))
       );
       jPanel1Layout.setVerticalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(cmdNuevo)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(cmdEditar)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(cmdEliminar)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );

       cmdAceptar.setText("Aceptar");
       cmdAceptar.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               cmdAceptarActionPerformed(evt);
           }
       });

       jLabel1.setText("Tipo Insumo");

       cmbTipoEstablecimiento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mano de Obra", "Materiales", "Servicios" }));

       
       cmdCancelar.setText("Cancelar");
       cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               cmdCancelarActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addComponent(jLabel1)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addComponent(cmbTipoEstablecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addGroup(layout.createSequentialGroup()
                       .addGap(126, 126, 126)
                       .addComponent(cmdAceptar)
                       .addGap(56, 56, 56)
                       .addComponent(cmdCancelar))
                   .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
               .addGap(18, 18, 18)
               .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap())
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(cmbTipoEstablecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel1))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addGroup(layout.createSequentialGroup()
                       .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                       .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(34, 34, 34)))
               .addGap(21, 21, 21))
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
               .addContainerGap(333, Short.MAX_VALUE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(cmdAceptar)
                   .addComponent(cmdCancelar))
               .addContainerGap())
       );

       pack();

   }// </editor-fold>

   private void cmdAceptarActionPerformed(java.awt.event.ActionEvent evt) {                                           
       // TODO add your handling code here:
	      setVisible(false); 
   }                                          

   private void cmdNuevoActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // TODO add your handling code here:
   }                                        

   private void cmdEditarActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {                                            
       // TODO add your handling code here:
   }                                           

   private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
	   setVisible(false); 
}

   
   /**
   * @param args the command line arguments
   */
   public static void main(String args[]) {
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new fInsumos().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify
   private javax.swing.JComboBox cmbTipoEstablecimiento;
   private javax.swing.JButton cmdAceptar;
   private javax.swing.JButton cmdEditar;
   private javax.swing.JButton cmdEliminar;
   private javax.swing.JButton cmdNuevo;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTable tblTabla;
   private javax.swing.JButton cmdCancelar;
   // End of variables declaration

}
