package ec.gov.senplades.planificador;

/**
*
* @author jalvarado
*/
public class fMuestra extends javax.swing.JFrame {

   /** Creates new form NewJFrame */
   public fMuestra(String sTexto) {
       initComponents();
       setTitle("Mensaje"); 
       txtMensaje.setText(sTexto); 
       setVisible(true); 
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   private void initComponents() {

       jScrollPane1 = new javax.swing.JScrollPane();
       txtMensaje = new javax.swing.JTextArea();
       cmdAceptar = new javax.swing.JButton();

       //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
       addWindowListener(new java.awt.event.WindowAdapter() {
           public void windowClosed(java.awt.event.WindowEvent evt) {
               formWindowClosed(evt);
           }
       });

       txtMensaje.setColumns(20);
       txtMensaje.setRows(5);
       jScrollPane1.setViewportView(txtMensaje);

       cmdAceptar.setText("Aceptar");
       cmdAceptar.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               cmdAceptarActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addContainerGap()
                       .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                   .addGroup(layout.createSequentialGroup()
                       .addGap(158, 158, 158)
                       .addComponent(cmdAceptar)))
               .addContainerGap())
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(cmdAceptar)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );

       pack();
   }// </editor-fold>

   private void cmdAceptarActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
	   setVisible(false); 
   }

   private void formWindowClosed(java.awt.event.WindowEvent evt) {
       // TODO add your handling code here:
   }

   /**
   * @param args the command line arguments
   */
   public static void main(String args[]) {
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new fMuestra("Prueba").setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify
   private javax.swing.JButton cmdAceptar;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextArea txtMensaje;
   // End of variables declaration

}
