package ec.gov.senplades.planificador;

import java.awt.geom.Point2D;
import java.util.ArrayList;

/*
 * fPuntual.java
 *
 * Created on 21/06/2010, 09:35:18 AM
 */

/**
 *
 * @author jalvarado
 */
public class fPoligonal extends javax.swing.JFrame {

	private fParametroInfraestructura oForma= null; 
	fInicio oFormaAnt; 
	int nTipoIntervencion ;
	
    /** Creates new form fPuntual */
    public fPoligonal(fInicio oFormaAnt,ArrayList<Point2D> aPuntos) {
        initComponents();
        Object [][] Datos = new Object[aPuntos.size()][5];
        int i=0; 
        for (Point2D oo: aPuntos) {
            Datos[i][0] = oo.getX(); 
            Datos[i][1] = oo.getY();
            Datos[i][2] = "";            
            Datos[i][3] = "";
            Datos[i][4] = "";            
            i++; 
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                Datos,
                new String [] {"UTM X", "UTM Y", "Area Censal", "Parroquia", "Canton" }
            ) {
                Class[] types = new Class [] {
                    java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
            });
        
        this.oFormaAnt = oFormaAnt; 
        txtId.setText("Poligonal-"+oFormaAnt.nPoligonal); 
        setVisible(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmdCoordenadas = new javax.swing.JButton();
        cmdAceptar = new javax.swing.JButton();
        cmdCancelar = new javax.swing.JButton();
        txtAreaCensal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cmdAgrega = new javax.swing.JButton();
        cmdEdita = new javax.swing.JButton();
        cmdElimina = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbProducto = new javax.swing.JComboBox();        
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        
        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Definición de poligono");

        jLabel1.setText("Código Sigtierra");

        cmdCoordenadas.setText("Carga Coordenadas");
        cmdCoordenadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCoordenadasActionPerformed(evt);
            }
        });

        cmdAceptar.setText("Aceptar");
        cmdAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAceptarActionPerformed(evt);
            }
        });

        cmdCancelar.setText("Cancelar");
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });

        txtAreaCensal.setText("                             ");

        jScrollPane1.setViewportView(jTable1);

        cmdAgrega.setText("Agrega");
        cmdAgrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgregaActionPerformed(evt);
            }
        });

        cmdEdita.setText("Edita");
        cmdEdita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditaActionPerformed(evt);
            }
        });

        cmdElimina.setText("Elimina");
        cmdElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminaActionPerformed(evt);
            }
        });

        jLabel2.setText("Producto:");

        cmbProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Banano", "Arroz", "Cebada", "Papa", "Trigo"  }));
        cmbProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductoActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre Identificador");

        txtId.setText("                                         ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(cmdAceptar)
                                .addGap(121, 121, 121)
                                .addComponent(cmdCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmdAgrega, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmdElimina, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmdEdita, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)))
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAreaCensal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(cmbProducto, 0, 193, Short.MAX_VALUE)
                            .addComponent(txtId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addComponent(cmdCoordenadas)
                        .addGap(61, 61, 61))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmdCoordenadas)
                    .addComponent(txtAreaCensal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdAgrega)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdEdita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdElimina))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdAceptar)
                            .addComponent(cmdCancelar))))
                .addContainerGap())
        );

        pack();

    }// </editor-fold>

    private void cmdAceptarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	oFormaAnt.nPoligonal++;     	
    	this.setVisible(false);    
    }                                          

    private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    	this.setVisible(false);    
    }                                           

    private void cmdCoordenadasActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void cmdAgregaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void cmdEditaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void cmdEliminaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void cmbProductoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fPoligonal(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JComboBox cmbProducto;    
    private javax.swing.JButton cmdAceptar;
    private javax.swing.JButton cmdAgrega;
    private javax.swing.JButton cmdCancelar;
    private javax.swing.JButton cmdCoordenadas;
    private javax.swing.JButton cmdEdita;
    private javax.swing.JButton cmdElimina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;    
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAreaCensal;
    // End of variables declaration
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtId;
}
