package ec.gov.senplades.planificador;

import javax.swing.DefaultListModel;

/**
*
* @author jalvarado
*/
public class fPonderadorDemanda extends javax.swing.JFrame {

	DefaultListModel mIndicador, mPonderador ; //= new DefaultListModel();  	
	
   /** Creates new form fPonderadorDemanda */
   public fPonderadorDemanda() {
       initComponents();
       setVisible(true);
       
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   private void initComponents() {

       jLabel1 = new javax.swing.JLabel();
       jScrollPane1 = new javax.swing.JScrollPane();
       lstIndicador = new javax.swing.JList();
       cmdCancelar = new javax.swing.JButton();
       jScrollPane2 = new javax.swing.JScrollPane();
       lstPonderador = new javax.swing.JList();
       jLabel2 = new javax.swing.JLabel();
       cmdAceptar = new javax.swing.JButton();
       jPanel1 = new javax.swing.JPanel();
       cmdDerecha = new javax.swing.JButton();
       cmdIzquierda = new javax.swing.JButton();
       cmdExplicacion = new javax.swing.JButton();

       //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
       setTitle("Indicadores ponderadores de la demanda");
       setAlwaysOnTop(true);
       addWindowListener(new java.awt.event.WindowAdapter() {
           public void windowClosed(java.awt.event.WindowEvent evt) {
               formWindowClosed(evt);
           }
       });

       jLabel1.setText("Indicadores");

       mIndicador = new DefaultListModel();
       mIndicador.addElement("% Pobreza");
       mIndicador.addElement("% Pobreza Extrema");       
       mIndicador.addElement("Deficiencia Educación");
       mIndicador.addElement("Morbilidad");
       mIndicador.addElement("Mortalidad Infantil");       
       mIndicador.addElement("% Familias con migrantes");
       mIndicador.addElement("%Desempleo");       
       lstIndicador.setModel(mIndicador);
       jScrollPane1.setViewportView(lstIndicador);

       cmdCancelar.setText("Cancelar");
       cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               cmdCancelarActionPerformed(evt);
           }
       });

       lstPonderador.setModel(new javax.swing.AbstractListModel() {
           String[] strings = { };
           public int getSize() { return strings.length; }
           public Object getElementAt(int i) { return strings[i]; }
       });
       jScrollPane2.setViewportView(lstPonderador);

       jLabel2.setText("Ponderadores");
       mPonderador = new DefaultListModel();
       
       cmdAceptar.setText("Aceptar");
       cmdAceptar.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               cmdAceptarActionPerformed(evt);
           }
       });

       cmdDerecha.setText(">");
       cmdDerecha.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               cmdDerechaActionPerformed(evt);
           }
       });

       cmdIzquierda.setText("<");
       cmdIzquierda.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               cmdIzquierdaActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
       jPanel1.setLayout(jPanel1Layout);
       jPanel1Layout.setHorizontalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(cmdIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
                   .addComponent(cmdDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)))
       );
       jPanel1Layout.setVerticalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(cmdDerecha)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(cmdIzquierda)
               .addContainerGap(15, Short.MAX_VALUE))
       );

       cmdExplicacion.setText("Explicación");
       cmdExplicacion.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               cmdExplicacionActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(26, 26, 26)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                           .addComponent(cmdAceptar)
                           .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addComponent(jLabel1))
               .addGap(17, 17, 17)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jLabel2)
                   .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(cmdCancelar))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
               .addContainerGap(472, Short.MAX_VALUE)
               .addComponent(cmdExplicacion)
               .addGap(22, 22, 22))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(cmdExplicacion)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
               .addComponent(jLabel2)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(52, 52, 52))
           .addGroup(layout.createSequentialGroup()
               .addGap(46, 46, 46)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                   .addGroup(layout.createSequentialGroup()
                       .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(83, 83, 83))
                   .addGroup(layout.createSequentialGroup()
                       .addComponent(jLabel1)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(cmdAceptar)
                   .addComponent(cmdCancelar)))
       );

       pack();
   }// </editor-fold>

   private void formWindowClosed(java.awt.event.WindowEvent evt) {
       // TODO add your handling code here:
   }

   private void cmdExplicacionActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
   }

   private void cmdAceptarActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
       setVisible(false);	   
   }

   private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
       setVisible(false);	   
   }

   private void cmdDerechaActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
	   int nIndex = lstIndicador.getSelectedIndex(); 
	   if (nIndex != -1) {
		   Object oSele = lstIndicador.getSelectedValue();
		   mPonderador.addElement(oSele); 
		   lstPonderador.setModel(mPonderador);
		   mIndicador.remove(nIndex);
		   lstIndicador.setModel(mIndicador);		   
	   }
 
	   
   }

   private void cmdIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
	   int nIndex = lstPonderador.getSelectedIndex(); 
	   if (nIndex != -1) {
		   Object oSele = lstPonderador.getSelectedValue();
		   mIndicador.addElement(oSele); 
		   lstIndicador.setModel(mIndicador);
		   mPonderador.remove(nIndex);
		   lstPonderador.setModel(mPonderador);		   
	   }
	   
	   
   }

   /**
   * @param args the command line arguments
   */
   public static void main(String args[]) {
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new fPonderadorDemanda().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify
   private javax.swing.JButton cmdAceptar;
   private javax.swing.JButton cmdCancelar;
   private javax.swing.JButton cmdDerecha;
   private javax.swing.JButton cmdExplicacion;
   private javax.swing.JButton cmdIzquierda;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JList lstIndicador;
   private javax.swing.JList lstPonderador;
   // End of variables declaration

}
