package ec.gov.senplades.planificador;

import java.awt.geom.Point2D;
import java.util.ArrayList;

import com.vividsolutions.jts.geom.Point;



/*
 * fPuntual.java
 *
 * Created on 21/06/2010, 09:35:18 AM
 */


/**
 *
 * @author jalvarado
 */
public class fPuntual extends javax.swing.JFrame  {

	
	private Point2D punto ; 
    private String sTipoCentro; 
    private boolean bAmpliacion;  
	ArrayList<Object []> parametros ; 
	private fParametroInfraestructura oForma= null; 
	fInicio oFormaAnt; 
	int nTipoIntervencion ;
	
    /** Creates new form fPuntual */
    public fPuntual(fInicio oFormaAnt, Point2D punto, String sCodigo) {
        this.oFormaAnt = oFormaAnt;
    	initComponents();
    	    	
        this.setVisible(true); 
        this.punto = punto; 
        txtX.setText( Double.toString(punto.getX()) ); 
        txtY.setText( Double.toString(punto.getY()) );
        txtAreaCensal.setText(sCodigo); 
        txtId.setText("Puntual-"+oFormaAnt.nPuntual); 
        
        sTipoCentro = this.cmbTipoCentro.getSelectedItem().toString();
        Object[] res = this.oFormaAnt.DB.TipoIntervencion.SelectPorNombre(new String [] {"Id"}, sTipoCentro); 
        nTipoIntervencion = (Integer) res[0];           
        parametros =  this.oFormaAnt.DB.Parametro.SelectPorFiltro(
     		   new String [] {"Nombre", "Default"} , new Object [][] {{"TipoIntervencion_id", nTipoIntervencion}} );

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbTipoCentro = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtX = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtY = new javax.swing.JTextField();
        cmdParametro = new javax.swing.JButton();
        cmdAceptar = new javax.swing.JButton();
        cmdCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtAreaCensal = new javax.swing.JTextField();

        txtPoblacionBase = new javax.swing.JTextField();
        cmdPoblacionObjetivo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRadio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();       
        
       // setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Intervención Puntual");

        jLabel1.setText("Tipo Infraestructura");

        ArrayList<Object []> oTipo =  this.oFormaAnt.DB.TipoIntervencion.SelectPorFiltro(
      		   new String [] {"Nombre"} , new Object [][] {{"Clase", oFormaAnt.claseIntervencion }} );    	
        
        String[] aTipo = new String[oTipo.size()];
        int i=0; 
        for (Object [] oo : oTipo ) {
        	 aTipo[i] = (String) oo[0]; 
        	 i++; 
        }
        
        cmbTipoCentro.setModel(new javax.swing.DefaultComboBoxModel(aTipo) );

        cmbTipoCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoCentroActionPerformed(evt);
            }
        });


        jLabel2.setText("UTM X:");

        jLabel3.setText("UTM Y");

        cmdParametro.setText("Parámetros");
        cmdParametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdParametroActionPerformed(evt);
            }
        });        

        cmdAceptar.setText("Aceptar");
        cmdAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAceptarActionPerformed(evt);
            }
        });

        cmdCancelar.setText("Cancelar");
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Area Censal");
        txtAreaCensal.setText("                             ");

        cmdPoblacionObjetivo.setText("Población Objetivo");
        cmdPoblacionObjetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPoblacionObjetivoActionPerformed(evt);
            }
        });

        jLabel5.setText("Población Base");
        txtPoblacionBase.setText("              ");
        txtAreaCensal.setText("                             ");

        jLabel6.setText("Radio acceso");        
        
        jLabel7.setText("Nombre Identificador");

        txtId.setText("                                         ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cmdAceptar)
                                .addGap(121, 121, 121)
                                .addComponent(cmdCancelar)
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPoblacionBase, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addGap(80, 80, 80)
                                .addComponent(cmdPoblacionObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbTipoCentro, javax.swing.GroupLayout.Alignment.LEADING, 0, 279, Short.MAX_VALUE))
                                        .addGap(61, 61, 61))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                                .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                                .addComponent(txtY, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAreaCensal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmdParametro)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(25, 25, 25)))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTipoCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtAreaCensal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdParametro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPoblacionBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdPoblacionObjetivo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdAceptar)
                    .addComponent(cmdCancelar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        

        
    }// </editor-fold>

    
    public int getXX() {
    	return (int) punto.getX(); 
    }

    public int getYY() {
    	return (int) punto.getY(); 
    }

    public String getTipoCentro() {
    	return sTipoCentro; 
    }

    public boolean getAmplicacion() {
    	return bAmpliacion; 
    }
    
    private void cmbTipoCentroActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    	
        sTipoCentro = this.cmbTipoCentro.getSelectedItem().toString();
        Object[] res = this.oFormaAnt.DB.TipoIntervencion.SelectPorNombre(new String [] {"Id"}, sTipoCentro); 
        nTipoIntervencion = (Integer) res[0];           
        parametros =  this.oFormaAnt.DB.Parametro.SelectPorFiltro(
      		   new String [] {"Nombre", "Default"} , new Object [][] {{"TipoIntervencion_id", nTipoIntervencion}} );    	
    }

    private void cmdParametroActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
       
       String sTipoCentro = this.cmbTipoCentro.getSelectedItem().toString();
       
       if (oForma == null) {

          oForma = new fParametroInfraestructura(sTipoCentro, parametros );
    	} else 
    	  oForma.setVisible(true); 	
             	
    }
   
    private void cmdAceptarActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    	this.punto.setLocation(Double.parseDouble(this.txtX.getText()),   
    	Double.parseDouble(this.txtY.getText()) );
     	
    	this.oFormaAnt.nPuntual++; 
        this.oFormaAnt.AgregaIntervencionPuntual(nTipoIntervencion, parametros);    	
    	this.setVisible(false); 


    }

    private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        this.punto = null;   
    	sTipoCentro = ""; 
    	this.setVisible(false);     	
    }

    private void cmdPoblacionObjetivoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
     	new fPonderadorDemanda(); 
}
    
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fPuntual(null, null, "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JComboBox cmbTipoCentro;
    private javax.swing.JButton cmdAceptar;
    private javax.swing.JButton cmdCancelar;
    private javax.swing.JButton cmdParametro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtX;
    private javax.swing.JTextField txtY;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtAreaCensal;
    private javax.swing.JButton cmdPoblacionObjetivo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtPoblacionBase;
    private javax.swing.JTextField txtRadio;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtId;
    
    // End of variables declaration



}
