/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * fLocaliza.java
 *
 * Created on 10/06/2010, 01:11:37 PM
 */

package ec.gov.senplades.planificador;

import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author jalvarado
 */
public class fRebalanceo extends javax.swing.JFrame {

    /** Creates new form fLocaliza */
    public fRebalanceo() {
        initComponents();
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroupModo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cmbTipoCentro = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        TxtDemanda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbAño = new javax.swing.JComboBox();
        cmdPoblacion = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cmdCapacidad = new javax.swing.JButton();
        cmdTerritorio = new javax.swing.JButton();
        cmdCancelar = new javax.swing.JButton();
        cmdEjecutar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeTerritorio = new javax.swing.JTree();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAreas = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbDistancia = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rebalanceo de Capacidades ");

        jLabel1.setText("Tipo Establecimiento:");

        cmbTipoCentro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escuelas", "Colegios", "Dispensarios", "Hospitales", "Oficinas Correo", "Estacion Policia", "Estacion Bombero" }));
        cmbTipoCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoCentroActionPerformed(evt);
            }
        });

        jLabel2.setText("Demanda:");

        TxtDemanda.setText("Niños de 5 a 11 años");

        jLabel3.setText("Año:");

        cmbAño.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020"  }));

        cmdPoblacion.setText("Población Objetivo");
        cmdPoblacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPoblacionActionPerformed(evt);
            }
        });

        cmdCapacidad.setText("Capacidad");
        cmdCapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCapacidadActionPerformed(evt);
            }
        });

        cmdTerritorio.setText("Territorio");
        cmdTerritorio.setText("Territorio");
        cmdTerritorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTerritorioActionPerformed(evt);
            }
        });

        
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmdCapacidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(cmdTerritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(cmdCapacidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdTerritorio))
        );

        cmdCancelar.setText("Cancelar");
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });

        cmdEjecutar.setText("Ejecutar");
        cmdEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEjecutarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTreeTerritorio);

        jLabel7.setText("Territorio");

        tblAreas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Area Censal", "Demanda", "Capacidad Actual", "Capacidad Nuevo"
            }
        ));
        jScrollPane2.setViewportView(tblAreas);

        jLabel8.setText("Areas Censales");

        jLabel10.setText("Distancia");

        cmbDistancia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Euclidana", "Tiempos", "Tiempos+Condiciones Económicas" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbAño, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTipoCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtDemanda, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(cmdEjecutar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addComponent(cmdCancelar)
                .addGap(108, 108, 108))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbTipoCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdPoblacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtDemanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdEjecutar)
                    .addComponent(cmdCancelar))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>

    private void cmdPoblacionActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void cmbTipoCentroActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
         if (this.cmbTipoCentro.getSelectedItem().toString()=="Escuelas")
	       this.TxtDemanda.setText("Niños entre 6 a 11 años");

	   if (this.cmbTipoCentro.getSelectedItem().toString()=="Colegios")
	       this.TxtDemanda.setText("Jovenes entre 12 a 17 años");

	   if (this.cmbTipoCentro.getSelectedItem().toString()=="Dispensarios")
	       this.TxtDemanda.setText("Poblacion general");

	   if (this.cmbTipoCentro.getSelectedItem().toString()=="Hospitales")
	       this.TxtDemanda.setText("Poblacion general");

    }                                             


     private void CargaArbol() {


       DefaultMutableTreeNode Ecuador = new DefaultMutableTreeNode( "Ecuador" );
       modelo = new DefaultTreeModel(Ecuador);
       jTreeTerritorio.setModel(modelo);

       DefaultMutableTreeNode Azuay = new DefaultMutableTreeNode( "Azuay" );
       DefaultMutableTreeNode Bolivar = new DefaultMutableTreeNode( "Bolivar" );
       DefaultMutableTreeNode Cañar = new DefaultMutableTreeNode( "Cañar" );

       modelo.insertNodeInto(Azuay, Ecuador,0);
       modelo.insertNodeInto(Bolivar,Ecuador, 1);
       modelo.insertNodeInto(Cañar, Ecuador,2);


       DefaultMutableTreeNode Cuenca = new DefaultMutableTreeNode("Cuenca");
       DefaultMutableTreeNode Giron = new DefaultMutableTreeNode("Giron");
       DefaultMutableTreeNode Gualaceo=new DefaultMutableTreeNode("Gualaceo");
       DefaultMutableTreeNode Guaranda = new DefaultMutableTreeNode("Guaranda");
       DefaultMutableTreeNode Chillanes=new DefaultMutableTreeNode("Chillanes");
       DefaultMutableTreeNode Chimbo=new DefaultMutableTreeNode("Chimbo");
       DefaultMutableTreeNode Azogues = new DefaultMutableTreeNode("Azoguez");
       DefaultMutableTreeNode Biblian=new DefaultMutableTreeNode("Biblian");
       DefaultMutableTreeNode Cañar2=new DefaultMutableTreeNode("Cañar");

       modelo.insertNodeInto(Cuenca, Azuay, 0);
       modelo.insertNodeInto(Giron, Azuay, 1);
       modelo.insertNodeInto(Gualaceo, Azuay,2);
       modelo.insertNodeInto(Guaranda,  Bolivar,0);
       modelo.insertNodeInto(Chillanes,  Bolivar,1);
       modelo.insertNodeInto(Chimbo, Bolivar, 2);
       modelo.insertNodeInto(Azogues, Cañar,0);
       modelo.insertNodeInto(Biblian, Cañar,1);
       modelo.insertNodeInto(Cañar2, Cañar,2);

       DefaultMutableTreeNode Cuenca2=new DefaultMutableTreeNode("Cuenca");
       DefaultMutableTreeNode Bellavista=new DefaultMutableTreeNode("Bellavista");
       DefaultMutableTreeNode Cañaribamba=new DefaultMutableTreeNode("Cañaribamba");

       modelo.insertNodeInto(Cuenca2 ,Cuenca, 0);
       modelo.insertNodeInto(Bellavista ,Cuenca, 1);
       modelo.insertNodeInto(Cañaribamba ,Cuenca, 2);

       DefaultMutableTreeNode Giron2=new DefaultMutableTreeNode("Giron");
       DefaultMutableTreeNode Asuncion2=new DefaultMutableTreeNode("Asuncion");

       modelo.insertNodeInto(Giron2 ,Giron,0);
       modelo.insertNodeInto(Asuncion2 ,Giron,1);

       DefaultMutableTreeNode Gualaceo2=new DefaultMutableTreeNode("Gualaceo");
       DefaultMutableTreeNode Daniel=new DefaultMutableTreeNode("Daniel Cordova Toral");

       modelo.insertNodeInto(Gualaceo2 ,Gualaceo,0);
       modelo.insertNodeInto(Daniel ,Gualaceo,1);

       DefaultMutableTreeNode Guaranda2=new DefaultMutableTreeNode("Guaranda");
       DefaultMutableTreeNode Angel=new DefaultMutableTreeNode("Angel Polivio Chavez");

       modelo.insertNodeInto(Guaranda2 ,Guaranda,0);
       modelo.insertNodeInto(Angel ,Guaranda,1);

       DefaultMutableTreeNode Chillanes2=new DefaultMutableTreeNode("Chillanes");
       DefaultMutableTreeNode Tambo=new DefaultMutableTreeNode("San Jose del Tambo");

       modelo.insertNodeInto(Chillanes2 ,Chillanes, 0);
       modelo.insertNodeInto(Tambo ,Chillanes, 1);

       DefaultMutableTreeNode Chimbo2=new DefaultMutableTreeNode("Chimbo");
       DefaultMutableTreeNode LaAsuncion=new DefaultMutableTreeNode("La Asuncion");

       modelo.insertNodeInto(Chimbo2 ,Chimbo, 0);
       modelo.insertNodeInto(LaAsuncion ,Chimbo, 1);

       DefaultMutableTreeNode Azogues2=new DefaultMutableTreeNode("Azogues");
       DefaultMutableTreeNode Borrero=new DefaultMutableTreeNode("Borrero");

       modelo.insertNodeInto(Azogues2 ,Azogues, 0);
       modelo.insertNodeInto(Borrero ,Azogues, 1);

       DefaultMutableTreeNode Biblian2=new DefaultMutableTreeNode("Biblian");
       DefaultMutableTreeNode Nazon=new DefaultMutableTreeNode("Nazon");

       modelo.insertNodeInto( Biblian2 ,Biblian,0);
       modelo.insertNodeInto( Nazon ,Biblian,1);

       DefaultMutableTreeNode Cañar3=new DefaultMutableTreeNode("Cañar");
       DefaultMutableTreeNode ChontaMarca=new DefaultMutableTreeNode("Chontamarca");

       modelo.insertNodeInto( Cañar3 ,Cañar2,0);
       modelo.insertNodeInto( ChontaMarca ,Cañar2,1);

       jTreeTerritorio.setModel(modelo);

   }




   private void cmdCapacidadActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
	   new fFiltro(); 
   }

   private void cmdTerritorioActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
	   new fFijaTerritorio(); 
   }

   private void cmdEjecutarActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
	    new fMuestra("Se encuentra ubicaciones optimas de acuerdo \n " +
	    		"con el modelo y los parametros ingresados. \n " +
	    		"Estas ubicaciones optimas junto con su área de \n " +
	    		"influencia son colocadas en el mapa "); 
   }

   private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
	   setVisible(false); 
   }
  

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fRebalanceo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField TxtDemanda;
    private javax.swing.ButtonGroup buttonGroupModo;
    private javax.swing.JComboBox cmbAño;
    private javax.swing.JComboBox cmbDistancia;
    private javax.swing.JComboBox cmbTipoCentro;
    private javax.swing.JButton cmdCancelar;
    private javax.swing.JButton cmdCapacidad;
    private javax.swing.JButton cmdEjecutar;
    private javax.swing.JButton cmdPoblacion;
    private javax.swing.JButton cmdTerritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTreeTerritorio;
    private javax.swing.JTable tblAreas;
    // End of variables declaration
   private DefaultTreeModel modelo;
}
